export const  GET_MASTER_DATA_REQUEST = "GET_MASTER_DATA_REQUEST";
export const  GET_MASTER_DATA_FAILURE = "GET_MASTER_DATA_FAILURE";
export const  GET_MASTER_DATA_SUCCESS = "GET_MASTER_DATA_SUCCESS";


export const  EDIT_MASTER_DATA_REQUEST = "EDIT_MASTER_DATA_REQUEST";
export const  EDIT_MASTER_DATA_FAILURE = "EDIT_MASTER_DATA_FAILURE";
export const  EDIT_MASTER_DATA_SUCCESS = "EDIT_MASTER_DATA_SUCCESS";